### ISSUE TITLE
[RFE] Please Add support for more Bugzilla API calls

### ISSUE THREAD

**Issue by jamacku** [Mossop/bugzilla-ts#40]
It would be nice to have access to more functions of Bugzilla API.

I'm building GitHub bot which would be able interconnect Bugzilla and GitHub and I would find especially useful things like:
- [x] [Ability to create new Bugs and update existing ones](https://bugzilla.readthedocs.io/en/latest/api/core/v1/bug.html#create-bug) - #74
- [x] [Ability to add comments](https://bugzilla.readthedocs.io/en/latest/api/core/v1/comment.html#create-comments) - #41 
- [x] [Support for attachements](https://bugzilla.readthedocs.io/en/latest/api/core/v1/attachment.html#attachments) - #81 

I know that it's a lot of work and I'm happy to help with implementing those functions.

**Comment by Mossop** [comment]
Yeah I'd love to see these things implemented but as this is a side project of mine and it already has the functionality I needed it for I don't have much time to do the implementation work. Happy to review and accept patches though.

**Comment by jamacku** [comment]
I completely understand that. I'll try to prepare some patches and let you know when they are ready for your review. Thanks

**Comment by jamacku** [comment]
This can be closed. Thank you so much for help with PR's @Mossop.
